import './globals.css'
//We don't need the library below; 
// import type {Metadata} from 'next'
import { Inter } from 'next/font/google'
//Importing the utility file
//Reusable Component
import {cn, constructMedata} from "../lib/utils"
import Navbar from "./Components/Navbar"
import Providers from './Components/Providers'

//Importing the Skeleton CSS library; 
import "react-loading-skeleton/dist/skeleton.css"
//Importing the simplebar css library; 
import "simplebar-react/dist/simplebar.min.css"

//Destructive Notifications, Toast, shadcn/ui library; 
import { Toaster } from "@/components/ui/toaster"

const inter = Inter({ subsets: ['latin'] })

//Replacing the following with a custom one
// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export const metadata = constructMedata ()


export default function RootLayout({
  children,
}:{
  children: React.ReactNode
}){
  return(
    <html lang="en" className='light'>
      <Providers>
        <body className={cn('min.screen font-sans antialiased grainy',inter.className)}>
            <Toaster/>
           <Navbar/>
           {children}
        </body>
      </Providers>
    </html>
  )
}